package trackingLog.mvc

import org.slf4j.Marker
import org.slf4j.MarkerFactory
import org.slf4j.LoggerFactory
import org.slf4j.spi.LocationAwareLogger

trait TrackingLogging {
  val trackingLogger: TrackingLogger = {
    TrackingLogger(LoggerFactory.getLogger(getClass).asInstanceOf[LocationAwareLogger])
  }
}

import LocationAwareLogger._
protected case class TrackingLogger(logger: LocationAwareLogger) extends TrackingId {

  /**
   * Give Log an identifier.
   * When searching in CloudWatch, if the unique value generated by UUID contains -, it will cause an error, so remove the -.
   */
  val marker: Marker = MarkerFactory.getMarker(generateUUID.toString().replace("-", ""))

  val fqcn = getClass.getName

  /**
   * Message only log
   */
  def info(message:  => String): Unit = { if (logger.isInfoEnabled)  logger.log(marker, fqcn, INFO_INT,  message, null, null) }
  def warn(message:  => String): Unit = { if (logger.isWarnEnabled)  logger.log(marker, fqcn, WARN_INT,  message, null, null) }
  def error(message: => String): Unit = { if (logger.isErrorEnabled) logger.log(marker, fqcn, ERROR_INT, message, null, null) }
  def debug(message: => String): Unit = { if (logger.isDebugEnabled) logger.log(marker, fqcn, DEBUG_INT, message, null, null) }
  def trace(message: => String): Unit = { if (logger.isTraceEnabled) logger.log(marker, fqcn, TRACE_INT, message, null, null) }

  /**
   * Handle messages and exceptions
   */
  def info(message:  => String, throwable: Throwable): Unit = { if (logger.isInfoEnabled)  logger.log(marker, fqcn, INFO_INT,  message, null, throwable) }
  def warn(message:  => String, throwable: Throwable): Unit = { if (logger.isWarnEnabled)  logger.log(marker, fqcn, WARN_INT,  message, null, throwable) }
  def error(message: => String, throwable: Throwable): Unit = { if (logger.isErrorEnabled) logger.log(marker, fqcn, ERROR_INT, message, null, throwable) }
  def debug(message: => String, throwable: Throwable): Unit = { if (logger.isDebugEnabled) logger.log(marker, fqcn, DEBUG_INT, message, null, throwable) }
  def trace(message: => String, throwable: Throwable): Unit = { if (logger.isTraceEnabled) logger.log(marker, fqcn, TRACE_INT, message, null, throwable) }

  /**
   * Handle messages and Array Object
   */
  def info(message:  => String, argArray: Array[Object]): Unit = { if (logger.isInfoEnabled)  logger.log(marker, fqcn, INFO_INT,  message, argArray, null) }
  def warn(message:  => String, argArray: Array[Object]): Unit = { if (logger.isWarnEnabled)  logger.log(marker, fqcn, WARN_INT,  message, argArray, null) }
  def error(message: => String, argArray: Array[Object]): Unit = { if (logger.isErrorEnabled) logger.log(marker, fqcn, ERROR_INT, message, argArray, null) }
  def debug(message: => String, argArray: Array[Object]): Unit = { if (logger.isDebugEnabled) logger.log(marker, fqcn, DEBUG_INT, message, argArray, null) }
  def trace(message: => String, argArray: Array[Object]): Unit = { if (logger.isTraceEnabled) logger.log(marker, fqcn, TRACE_INT, message, argArray, null) }
}
